"""add_sender_id_to_tech_train_invites

Revision ID: 65801be797f8
Revises: e8a1a22011aa
Create Date: 2024-04-30 04:07:24.583375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65801be797f8'
down_revision: Union[str, None] = 'e8a1a22011aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_train_invites', sa.Column('sender_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_train_invites', 'sender_id')
    # ### end Alembic commands ###
