"""add_models

Revision ID: f0ad03a86d55
Revises: 
Create Date: 2024-04-26 03:30:06.207717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ad03a86d55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_message_delete_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_message_delete_targets_guild_id'), 'discord_message_delete_targets', ['guild_id'], unique=False)
    op.create_table('discord_room_announce_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_room_announce_targets_guild_id'), 'discord_room_announce_targets', ['guild_id'], unique=False)
    op.create_table('discord_thread_create_notify_ignore_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_thread_create_notify_ignore_targets_guild_id'), 'discord_thread_create_notify_ignore_targets', ['guild_id'], unique=False)
    op.create_table('discord_thread_create_notify_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_thread_create_notify_roles_guild_id'), 'discord_thread_create_notify_roles', ['guild_id'], unique=False)
    op.create_table('discord_thread_keep_ignore_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('thread_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_thread_keep_ignore_targets_guild_id'), 'discord_thread_keep_ignore_targets', ['guild_id'], unique=False)
    op.create_table('discord_thread_timeline_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_thread_timeline_channels_guild_id'), 'discord_thread_timeline_channels', ['guild_id'], unique=False)
    op.create_index(op.f('ix_discord_thread_timeline_channels_parent_channel_id'), 'discord_thread_timeline_channels', ['parent_channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discord_thread_timeline_channels_parent_channel_id'), table_name='discord_thread_timeline_channels')
    op.drop_index(op.f('ix_discord_thread_timeline_channels_guild_id'), table_name='discord_thread_timeline_channels')
    op.drop_table('discord_thread_timeline_channels')
    op.drop_index(op.f('ix_discord_thread_keep_ignore_targets_guild_id'), table_name='discord_thread_keep_ignore_targets')
    op.drop_table('discord_thread_keep_ignore_targets')
    op.drop_index(op.f('ix_discord_thread_create_notify_roles_guild_id'), table_name='discord_thread_create_notify_roles')
    op.drop_table('discord_thread_create_notify_roles')
    op.drop_index(op.f('ix_discord_thread_create_notify_ignore_targets_guild_id'), table_name='discord_thread_create_notify_ignore_targets')
    op.drop_table('discord_thread_create_notify_ignore_targets')
    op.drop_index(op.f('ix_discord_room_announce_targets_guild_id'), table_name='discord_room_announce_targets')
    op.drop_table('discord_room_announce_targets')
    op.drop_index(op.f('ix_discord_message_delete_targets_guild_id'), table_name='discord_message_delete_targets')
    op.drop_table('discord_message_delete_targets')
    # ### end Alembic commands ###
