"""fix_room_open_data_structure

Revision ID: fac5ef52ade0
Revises: f26d0a8ff8c1
Create Date: 2024-04-26 04:46:15.361550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac5ef52ade0'
down_revision: Union[str, None] = 'f26d0a8ff8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_act126_open_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_close_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_act126_announce_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open_status_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['open_status_id'], ['discord_act126_open_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('discord_manager_in_act126_open_data_id_fkey', 'discord_manager_in_act126', type_='foreignkey')
    op.drop_table('discord_act126_open_data')
    op.add_column('discord_manager_in_act126', sa.Column('open_status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'discord_manager_in_act126', 'discord_act126_open_status', ['open_status_id'], ['id'])
    op.drop_column('discord_manager_in_act126', 'open_data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_manager_in_act126', sa.Column('open_data_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'discord_manager_in_act126', type_='foreignkey')
    op.create_foreign_key('discord_manager_in_act126_open_data_id_fkey', 'discord_manager_in_act126', 'discord_act126_open_data', ['open_data_id'], ['id'])
    op.drop_column('discord_manager_in_act126', 'open_status_id')
    op.create_table('discord_act126_open_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('open_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estimated_close_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('close_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='discord_act126_open_data_pkey')
    )
    op.drop_table('discord_act126_announce_messages')
    op.drop_table('discord_act126_open_status')
    # ### end Alembic commands ###
