"""add_techtrain_models

Revision ID: e8a1a22011aa
Revises: 2ffce2cb4e05
Create Date: 2024-04-30 03:58:03.266200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a1a22011aa'
down_revision: Union[str, None] = '2ffce2cb4e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_train_invite_management_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_train_invite_management_channels_guild_id'), 'tech_train_invite_management_channels', ['guild_id'], unique=False)
    op.create_table('tech_train_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.BigInteger(), nullable=False),
    sa.Column('invite_url', sa.BigInteger(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_train_invites_guild_id'), 'tech_train_invites', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_train_invites_guild_id'), table_name='tech_train_invites')
    op.drop_table('tech_train_invites')
    op.drop_index(op.f('ix_tech_train_invite_management_channels_guild_id'), table_name='tech_train_invite_management_channels')
    op.drop_table('tech_train_invite_management_channels')
    # ### end Alembic commands ###
