"""change_datatypes_in_tech_train_invites

Revision ID: d57736c1cab9
Revises: 65801be797f8
Create Date: 2024-04-30 04:23:30.591073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd57736c1cab9'
down_revision: Union[str, None] = '65801be797f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tech_train_invites', 'email',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tech_train_invites', 'invite_url',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tech_train_invites', 'invite_url',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('tech_train_invites', 'email',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
