"""fix_column_name_in_tech_train_invite

Revision ID: 7bd7db78a629
Revises: d57736c1cab9
Create Date: 2024-04-30 05:19:28.072787

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7bd7db78a629'
down_revision: Union[str, None] = 'd57736c1cab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column email <-> invite_url
    op.alter_column('tech_train_invites', 'email', new_column_name='temp',
                    existing_type=sa.String(),
                    existing_nullable=False)
    op.alter_column('tech_train_invites', 'invite_url', new_column_name='email',
                    existing_type=sa.String(),
                    existing_nullable=False)
    op.alter_column('tech_train_invites', 'temp', new_column_name='invite_url',
                    existing_type=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column email <-> invite_url
    op.alter_column('tech_train_invites', 'invite_url', new_column_name='temp',
                    existing_type=sa.String(),
                    existing_nullable=False)
    op.alter_column('tech_train_invites', 'email', new_column_name='invite_url',
                    existing_type=sa.String(),
                    existing_nullable=False)
    op.alter_column('tech_train_invites', 'temp', new_column_name='email',
                    existing_type=sa.String(),
                    existing_nullable=False)
    # ### end Alembic commands ###
