"""fix_room_open_data_structure

Revision ID: 7234b2f78d8f
Revises: fac5ef52ade0
Create Date: 2024-04-26 04:59:14.888195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7234b2f78d8f'
down_revision: Union[str, None] = 'fac5ef52ade0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_announce_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discord_announce_messages_guild_id'), 'discord_announce_messages', ['guild_id'], unique=False)
    op.create_table('discord_in_room_managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('estimated_close_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('discord_manager_in_act126')
    op.drop_table('discord_act126_announce_messages')
    op.drop_table('discord_act126_open_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_act126_announce_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('open_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['open_status_id'], ['discord_act126_open_status.id'], name='discord_act126_announce_messages_open_status_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discord_act126_announce_messages_pkey')
    )
    op.create_table('discord_manager_in_act126',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('open_status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['open_status_id'], ['discord_act126_open_status.id'], name='discord_manager_in_act126_open_status_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='discord_manager_in_act126_pkey')
    )
    op.create_table('discord_act126_open_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('open_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('estimated_close_at', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='discord_act126_open_status_pkey')
    )
    op.drop_table('discord_in_room_managers')
    op.drop_index(op.f('ix_discord_announce_messages_guild_id'), table_name='discord_announce_messages')
    op.drop_table('discord_announce_messages')
    # ### end Alembic commands ###
