"""add_room_open_data

Revision ID: f26d0a8ff8c1
Revises: f0ad03a86d55
Create Date: 2024-04-26 04:23:00.449994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26d0a8ff8c1'
down_revision: Union[str, None] = 'f0ad03a86d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_act126_open_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_close_at', sa.String(), nullable=False),
    sa.Column('close_at', sa.DateTime(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_manager_in_act126',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('open_data_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['open_data_id'], ['discord_act126_open_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_manager_in_act126')
    op.drop_table('discord_act126_open_data')
    # ### end Alembic commands ###
